# Generated by Django 5.1 on 2024-10-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.HZAqsAq7TWsyuco6DYKWXQHaEq?rs=1&pid=ImgDetMain', max_length=500),
        ),
    ]
